// Public tests for the color-correction matrix path.
//
// Every fixture is synthetic or comes from a published reference table, so the
// numerical behavior is checkable without any chart capture. Tolerances match
// the ones the archive tests use; a public test is not a place to tighten a
// bound around whatever the implementation currently prints.

#include <array>
#include <cmath>
#include <cstdlib>
#include <iostream>
#include <limits>
#include <string>
#include <vector>

#include "camera_iq/camera_rgb.hpp"
#include "camera_iq/colorimetry.hpp"

namespace {

using camera_iq::CameraRgbPatch;
using camera_iq::Lab;
using camera_iq::Xyz;

int failures = 0;

void check(bool condition, const std::string& what) {
  if (!condition) {
    std::cerr << "FAIL: " << what << "\n";
    ++failures;
  }
}

void check_near(double actual, double expected, double tolerance,
                const std::string& what) {
  if (!(std::abs(actual - expected) <= tolerance)) {
    std::cerr << "FAIL: " << what << " (expected " << expected << " +/- "
              << tolerance << ", got " << actual << ")\n";
    ++failures;
  }
}

// D65 with Y = 1, matching the scale used for the synthetic targets below.
constexpr Xyz kWhite{0.95047, 1.0, 1.08883};

// An arbitrary well-conditioned matrix. Nothing about it is special; the point
// is that the solver must return exactly this, not something close to it.
constexpr std::array<std::array<double, 3>, 3> kKnownMatrix{{
    {0.42, 0.35, 0.18},
    {0.21, 0.71, 0.07},
    {0.02, 0.12, 0.95},
}};

Xyz multiply(const std::array<std::array<double, 3>, 3>& m,
             const CameraRgbPatch& rgb) {
  return Xyz{m[0][0] * rgb.r + m[0][1] * rgb.g + m[0][2] * rgb.b,
             m[1][0] * rgb.r + m[1][1] * rgb.g + m[1][2] * rgb.b,
             m[2][0] * rgb.r + m[2][1] * rgb.g + m[2][2] * rgb.b};
}

// A spread of patches that is not collinear, so the 3x3 design is full rank.
std::vector<CameraRgbPatch> synthetic_patches() {
  return {
      {0.90, 0.88, 0.86}, {0.62, 0.60, 0.58}, {0.36, 0.35, 0.34},
      {0.19, 0.18, 0.18}, {0.09, 0.09, 0.09}, {0.04, 0.04, 0.04},
      {0.55, 0.22, 0.14}, {0.19, 0.45, 0.20}, {0.13, 0.20, 0.52},
      {0.60, 0.55, 0.15}, {0.48, 0.16, 0.38}, {0.14, 0.46, 0.50},
      {0.72, 0.40, 0.12}, {0.25, 0.30, 0.65}, {0.66, 0.24, 0.28},
      {0.80, 0.66, 0.20}, {0.44, 0.18, 0.46}, {0.16, 0.52, 0.34},
  };
}

std::vector<Xyz> targets_from(const std::vector<CameraRgbPatch>& rgb,
                              const std::array<std::array<double, 3>, 3>& m) {
  std::vector<Xyz> out;
  out.reserve(rgb.size());
  for (const auto& patch : rgb) out.push_back(multiply(m, patch));
  return out;
}

void test_known_matrix_is_recovered_exactly() {
  const auto rgb = synthetic_patches();
  const auto target = targets_from(rgb, kKnownMatrix);
  const auto fit = camera_iq::fit_rgb_to_xyz_ccm(rgb, target, kWhite);

  check(fit.patch_count == rgb.size(), "the fit reports every patch it saw");
  for (int row = 0; row < 3; ++row) {
    for (int col = 0; col < 3; ++col) {
      check_near(fit.matrix[row][col], kKnownMatrix[row][col], 1e-10,
                 "least squares recovers the generating matrix");
    }
  }
  // Data generated by an exact linear map has no residual. A non-zero error
  // here would mean the solver is not solving what its API specifies.
  check_near(fit.mean_delta_e_2000, 0.0, 1e-9,
             "an exactly linear relationship leaves no color difference");
  check_near(fit.max_delta_e_76, 0.0, 1e-9,
             "an exactly linear relationship leaves no dE76 residual");
}

void test_apply_and_evaluate_agree() {
  const auto rgb = synthetic_patches();
  const auto target = targets_from(rgb, kKnownMatrix);
  const auto mapped = camera_iq::apply_ccm(kKnownMatrix, rgb[6]);
  const auto expected = multiply(kKnownMatrix, rgb[6]);
  check_near(mapped.x, expected.x, 1e-12, "apply_ccm matches the definition");
  check_near(mapped.y, expected.y, 1e-12, "apply_ccm matches the definition");
  check_near(mapped.z, expected.z, 1e-12, "apply_ccm matches the definition");

  const auto evaluation =
      camera_iq::evaluate_rgb_to_xyz_ccm(kKnownMatrix, rgb, target, kWhite);
  check(evaluation.patch_count == rgb.size(),
        "evaluation covers every supplied patch");
  check_near(evaluation.mean_delta_e_2000, 0.0, 1e-9,
             "evaluating the generating matrix on its own data is exact");
}

void test_heldout_differs_from_training_on_nonlinear_data() {
  // The whole point of held-out evaluation is that it can disagree with
  // training error. Linear data cannot show that, so the targets here are
  // bent by a quadratic term no 3x3 matrix can represent.
  auto rgb = synthetic_patches();
  auto target = targets_from(rgb, kKnownMatrix);
  for (std::size_t i = 0; i < target.size(); ++i) {
    const double g = rgb[i].g;
    target[i].y += 0.35 * g * g;
    target[i].x -= 0.20 * g * g;
  }

  const auto fit = camera_iq::fit_rgb_to_xyz_ccm(rgb, target, kWhite);
  const auto cv =
      camera_iq::cross_validate_rgb_to_xyz_ccm(rgb, target, kWhite, 5);

  check(cv.patch_count == rgb.size(),
        "cross-validation evaluates every patch exactly once");
  check(cv.fold_count == 5, "the requested fold count is honored");
  check(fit.mean_delta_e_2000 > 0.0,
        "a nonlinear relationship leaves a training residual");
  check(cv.mean_delta_e_2000 - fit.mean_delta_e_2000 > 1.0,
        "the nonlinear fixture creates a material held-out gap");
}

void test_fold_assignment_is_deterministic() {
  auto rgb = synthetic_patches();
  auto target = targets_from(rgb, kKnownMatrix);
  for (std::size_t i = 0; i < target.size(); ++i) {
    target[i].y += 0.35 * rgb[i].g * rgb[i].g;
  }
  const auto first = camera_iq::cross_validate_rgb_to_xyz_ccm(rgb, target, kWhite, 5);
  const auto second = camera_iq::cross_validate_rgb_to_xyz_ccm(rgb, target, kWhite, 5);
  check_near(second.mean_delta_e_2000, first.mean_delta_e_2000, 0.0,
             "repeating cross-validation gives a bit-identical result");
  check_near(second.max_delta_e_2000, first.max_delta_e_2000, 0.0,
             "the worst held-out patch is the same on repeat");
}

void test_lightness_selection_and_dark_diagnostics() {
  const auto rgb = synthetic_patches();
  const auto target = targets_from(rgb, kKnownMatrix);
  const auto selection =
      camera_iq::select_reference_lightness(target, kWhite, 25.0);

  check(selection.max_lstar == 25.0, "the selection records its own threshold");
  check(!selection.kept_indices.empty(), "a mixed chart keeps some patches");
  check(selection.kept_indices.size() < target.size(),
        "a mixed chart also excludes some patches");
  for (const std::size_t index : selection.kept_indices) {
    const auto lab = camera_iq::xyz_to_lab(target[index], kWhite);
    check(lab.l >= 25.0, "every kept patch is at or above the threshold");
  }

  const auto dark = camera_iq::diagnose_dark_patches(rgb, target, kWhite,
                                                     kKnownMatrix, 25.0);
  check(dark.patch_count + selection.kept_indices.size() == target.size(),
        "kept and excluded subsets partition the chart");
  check(dark.max_lstar == 25.0, "the diagnostic records its own threshold");
}

void test_published_ciede2000_reference_pairs() {
  // Supplementary pairs from Sharma, Wu, and Dalal (2005),
  // https://doi.org/10.1002/col.20070, at the tolerance the source tests use.
  // These catch the hue-rotation and chroma-weighting terms that a naive
  // implementation gets wrong.
  check_near(camera_iq::delta_e_2000({50.0, 2.6772, -79.7751},
                                     {50.0, 0.0, -82.7485}),
             2.0425, 1e-4, "CIEDE2000 reference pair 1");
  check_near(camera_iq::delta_e_2000({50.0, 3.1571, -77.2803},
                                     {50.0, 0.0, -82.7485}),
             2.8615, 1e-4, "CIEDE2000 reference pair 2");
  check_near(camera_iq::delta_e_2000({50.0, 2.8361, -74.0200},
                                     {50.0, 0.0, -82.7485}),
             3.4412, 1e-4, "CIEDE2000 reference pair 3");
  check_near(camera_iq::delta_e_2000({50.0, -1.3802, -84.2814},
                                     {50.0, 0.0, -82.7485}),
             1.0000, 1e-4, "CIEDE2000 reference pair 4");
  check_near(camera_iq::delta_e_2000({50.0, 0.0, 0.0}, {50.0, -1.0, 2.0}),
             2.3669, 1e-4, "CIEDE2000 neutral-chroma edge case");
  check_near(camera_iq::delta_e_2000({50.0, -1.0, 2.0}, {50.0, 0.0, 0.0}),
             2.3669, 1e-4, "CIEDE2000 is symmetric on that edge case");

  // dE76 is a plain Euclidean distance; keeping it checkable separates a
  // metric bug from a color-space bug.
  check_near(camera_iq::delta_e_76({50.0, 0.0, 0.0}, {53.0, 4.0, 0.0}), 5.0,
             1e-12, "dE76 is Euclidean in Lab");
}

void test_lab_round_trip() {
  const Xyz xyz{0.35, 0.42, 0.19};
  const auto lab = camera_iq::xyz_to_lab(xyz, kWhite);
  const auto back = camera_iq::lab_to_xyz(lab, kWhite);
  check_near(back.x, xyz.x, 1e-12, "Lab round-trip preserves X");
  check_near(back.y, xyz.y, 1e-12, "Lab round-trip preserves Y");
  check_near(back.z, xyz.z, 1e-12, "Lab round-trip preserves Z");
  check_near(camera_iq::xyz_to_lab(kWhite, kWhite).l, 100.0, 1e-9,
             "the reference white has L* = 100");
}

void test_refusals() {
  const auto rgb = synthetic_patches();
  const auto target = targets_from(rgb, kKnownMatrix);

  bool threw = false;
  try {
    std::vector<Xyz> short_target(target.begin(), target.end() - 1);
    (void)camera_iq::fit_rgb_to_xyz_ccm(rgb, short_target, kWhite);
  } catch (const std::exception&) {
    threw = true;
  }
  check(threw, "mismatched patch and target counts are refused");

  // Every patch on one line through the origin: the 3x3 design is rank 1, so
  // there is no unique solution and the fit must say so rather than return
  // whatever the elimination produces.
  threw = false;
  try {
    std::vector<CameraRgbPatch> collinear;
    std::vector<Xyz> collinear_target;
    for (int i = 1; i <= 8; ++i) {
      const double s = 0.1 * i;
      collinear.push_back({s, s, s});
      collinear_target.push_back(multiply(kKnownMatrix, {s, s, s}));
    }
    (void)camera_iq::fit_rgb_to_xyz_ccm(collinear, collinear_target, kWhite);
  } catch (const std::exception&) {
    threw = true;
  }
  check(threw, "a rank-deficient design is refused");

  threw = false;
  try {
    auto bad = rgb;
    bad[3].g = std::numeric_limits<double>::quiet_NaN();
    (void)camera_iq::fit_rgb_to_xyz_ccm(bad, target, kWhite);
  } catch (const std::exception&) {
    threw = true;
  }
  check(threw, "a non-finite input sample is refused");

  threw = false;
  try {
    (void)camera_iq::cross_validate_rgb_to_xyz_ccm(rgb, target, kWhite, 0);
  } catch (const std::exception&) {
    threw = true;
  }
  check(threw, "a zero fold count is refused");
}

}  // namespace

int main() {
  test_known_matrix_is_recovered_exactly();
  test_apply_and_evaluate_agree();
  test_heldout_differs_from_training_on_nonlinear_data();
  test_fold_assignment_is_deterministic();
  test_lightness_selection_and_dark_diagnostics();
  test_published_ciede2000_reference_pairs();
  test_lab_round_trip();
  test_refusals();

  if (failures != 0) {
    std::cerr << failures << " colorimetry test(s) failed\n";
    return EXIT_FAILURE;
  }
  std::cout << "color-correction matrix tests passed\n";
  return EXIT_SUCCESS;
}
